### ISSUE TITLE
Exception error; X is not an RSS file

### ISSUE THREAD

**Issue by anewuser** [steenhansen/podcast-downloader#1]
I've tried to use your program on Windows 10 LTSC, but kept getting these errors:

![Screenshot 2021-05-05 080641](https://user-images.githubusercontent.com/6733770/117132238-ef747680-ad78-11eb-8941-4f674fefdb2f.png)

![Screenshot 2021-05-05 080653](https://user-images.githubusercontent.com/6733770/117132249-f56a5780-ad78-11eb-9ade-efa2b8171b71.png)

Example URLs:

`http://historyofhousemusic.org/feed/podcast/`

`https://djmal.podomatic.com/rss2.xml`

**Comment by steenhansen** [comment]
Hello,
I am sorry you had a problem with the program. There is nothing wrong the the podcast feeds, it is the program.
I remember being somewhat lazy with the below error, not giving a full account, and just assuming the RSS file was bad.
I don't get the below error, but when I try to save to "C:" the program just ignores the command, no error message.

So I will change the program to give the "reason" for the bug. And also the location of attempted saving.
Questions:- have you tried downloading to your desktop? 
- have you tried downloading to your home folder?
I am not familiar with Windows 10 LTSC, the program was developed on Windows 7. 

Give me a week, and I will change the executable, email you, and then the error messages may help.Steen

    On Wednesday, May 5, 2021, 4:10:03 a.m. PDT, anewuser ***@***.***> wrote:  
 
 


I've tried to use your program on Windows 10 LTSC, but kept getting these errors:





Example URLs:

http://historyofhousemusic.org/feed/podcast/

https://djmal.podomatic.com/rss2.xml

**Comment by anewuser** [comment]
Those errors appear when I click on the "Read Podcast Feed" button, so I don't even get the list of episodes to download.

When I enter `https://djmal.podomatic.com/rss2.xml`, my firewall doesn't detect any connection attempt at all. It does connect to the server if I change `https` to `http`, but then fails again with the same error messages.

The console version doesn't work either. It says, `Cancelled with escape key or does not exist. Hit any key to continue.`

**Comment by steenhansen** [comment]
Hello,
For some reason I cannot stop programs from accessing the Internet on my computer via the firewall, somewhat distressing I must say. I can only turn off all the programs or none. Maybe it is because of my "Home" edition, I don't know.
The only thing I can think of is that your LTSC Windows has some more security than my Windows, it seems to me that's what some of the websites I read said.
You sound a little more knowledgeable than me on the subject, and my well have already tried this, but this is the best I can do. Try copying the steps below. If this doesn't help then I suggest using another computer. BTW, I noticed the old files you are interested in, you had better get them before they disappear.
Good Luck,Steen






    On Thursday, May 6, 2021, 10:38:48 a.m. PDT, anewuser ***@***.***> wrote:  
 
 


Those errors appear when I click on the "Read Podcast Feed" button, so I don't even get the list of episodes to download.

When I enter https://djmal.podomatic.com/rss2.xml, my firewall doesn't detect any connection attempt at all. It does connect to the server if I change https to http, but then fails again with the same error messages.

The console version doesn't work either. It says, Cancelled with escape key or does not exist. Hit any key to continue.

**Comment by anewuser** [comment]
Thank you for your replies. 

I'm sorry for the confusion. I didn't need to mention "LTSC" in my first post. When it comes to end-user applications, the only practical difference between it and the mainstream editions of Windows 10 is that the LTSC version has no "bloat" and stays frozen some versions behind instead of getting big changes every semester. The only software I've stumbled upon that I can't use on it are some new tools made by Microsoft developers themselves, like the new [Windows Terminal](https://www.microsoft.com/p/windows-terminal/9n0dx20hk701).

I ended up using [gPodder](https://gpodder.github.io/) to download those podcasts. My only problem with it is that it's optimized for Linux, and the Windows version comes with thousands of tiny files, but that's just a minor annoyance. It does the job well.
